name: Python CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install

      - name: Check code formatting with ruff
        run: poetry run ruff format --check .

      - name: Run ruff linters
        run: poetry run ruff check .